### ISSUE TITLE
iroha.protocol.Signature.public_key' contains invalid UTF-8 data when parsing a protocol buffer

### ISSUE THREAD

**Issue by aleksandrovych** [ERussel/IrohaCommunication#1]
Hi @ERussel ,
TxProcessor there are no transactions to be committed
[libprotobuf ERROR /tmp/protobuf/src/google/protobuf/wire_format_lite.cc:629] String field 'iroha.protocol.Signature.public_key' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 

After I launch a project, I see this error in iroha console. I pull master branch of iroha and launch 'latest' docker container

**Comment by ERussel** [comment]
Hi @aleksandrovych 

Please, checkout latest changes in develop branch. Support for the latest iroha (rc2) has been added. However integration tests are in progress to be sure that all features works as expected with iroha.
